# Usage:
#   conda build . -c defaults -c conda-forge

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
#{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
package:
  name: libarctern
  version: {{ version }}

source:
  path: ../../../..

# ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-section
build:
  number: {{ git_revision_count }}
  string: {{ git_revision_count }}
  script_env:
    - CC
    - CXX

requirements:
  build:
    - cmake>=3.14
    - gdal ==3.0.4
    - pyarrow ==0.16.0
    - rapidjson ==1.1.0

  run:
    - gdal ==3.0.4
    - pyarrow ===0.16.0
    - rapidjson ==1.1.0

test:
  commands:
    # headers
    # - test -f $PREFIX/include/

    # shared
    - test -f $PREFIX/lib/libminiz.so            # [linux]
    - test -f $PREFIX/lib/libarctern.so         # [linux]
    
    # absence of static libraries
    - test ! -f $PREFIX/lib/libminiz.a           # [unix]
    - test ! -f $PREFIX/lib/libarctern.a        # [unix]

    # conda tools

about:
  home: http://www.github.com/zilliztech/arctern
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary:  C++ library for Arctern
