\o @path@/expected/results/st_intersects.out
select st_intersects('POINT (1 8)'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POINT (1 8)'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (1 1,3 4)'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT (3 4)'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3)'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((2 4,1 9,1 8))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING ((1 1,3 4,1 1))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON ((0 0,0 4,4 4,0 0))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('POINT EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('LINESTRING EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('POLYGON EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOINT EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTILINESTRING EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POINT (1 8)'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOINT (1 1,3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOINT (3 4)'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3)'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'LINESTRING (1 1,1 2,2 3,1 1)'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTILINESTRING ((2 4,1 9,1 8))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTILINESTRING ((1 1,3 4,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POLYGON ((1 1,1 2,2 2,2 1,1 1))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POLYGON ((0 0,0 4,2 2,4 4,4 0,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POLYGON ((0 0,0 4,4 4,0 0))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOLYGON (((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOLYGON (((1 1,1 2,2 2,2 1,1 1)),((0 0,1 -1,1 1,-2 3,0 0)))'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'LINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'POLYGON EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOINT EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTILINESTRING EMPTY'::geometry) as geos;
select st_intersects('MULTIPOLYGON EMPTY'::geometry, 'MULTIPOLYGON EMPTY'::geometry) as geos;
\o
