# Usage:
#   conda build . -c defaults -c conda-forge -c nvidia

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v').replace('-', '.') + environ.get('VERSION_SUFFIX', '') %}
# {% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '10.0').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: arctern
  version: {{ version }}

source:
  path: ../../../..

# ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-section
build:
  number: {{ git_revision_count }}
  string: py{{ py_version }}_cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX

requirements:
  build:
    - libnetcdf ==4.7.3
    - cmake>=3.14
    - gdal ==3.0.4
    - pyarrow ==0.17.1
    - rapidjson ==1.1.0
    - python
    - Cython ==0.29.15
    - setuptools
    - koalas ==1.0.0
    - fiona

  host:
    - cudatoolkit {{ cuda_version }}.*

  run:
    - python
    - libnetcdf ==4.7.3
    - gdal ==3.0.4
    - pyarrow ===0.17.1
    - rapidjson ==1.1.0
    - koalas ==1.0.0
    - fiona

test:
  commands:
    # headers
    # - test -f $PREFIX/include/

    # shared
    - test -f $PREFIX/lib/libminiz.so            # [linux]
    - test -f $PREFIX/lib/libarctern.so         # [linux]
    
    # absence of static libraries
    - test ! -f $PREFIX/lib/libminiz.a           # [unix]
    - test ! -f $PREFIX/lib/libarctern.a        # [unix]

    # python
    - export PYTHONPATH=$PREFIX/lib:$PYTHONPATH
    - python -c "import arctern"
    # - python -c "import arctern_spark" # pyspark is required
    - python -c "import arctern_pyspark"

    # conda tools

about:
  home: http://www.github.com/zilliztech/arctern
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: library for Arctern
