version: '2.3'

services:
  spark-master:
    image: registry.zilliz.com/arctern/arctern-spark-gpu:v0.1.0-ubuntu18.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
  spark-worker:
    image: registry.zilliz.com/arctern/arctern-spark-gpu:v0.1.0-ubuntu18.04
    runtime: nvidia
    depends_on:
      - spark-master
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
