export const PointConfig = {
  id: 'pointmap',
  type: 'PointMap',
  title: '纽约出租车总收入',
  mapTheme: 'mapbox://styles/mapbox/dark-v9',
  source: 'nyc_taxi',
  isServerRender: true,
  layout: {
    w: 12,
    h: 29.5,
    x: 0,
    y: 0,
    i: 'pointmap',
    minW: 1,
    minH: 8,
    moved: false,
    static: false,
  },
  center: {lng: -73.91634373065904, lat: 40.54847545087728},
  zoom: 9.407634540298755,
  dimensions: [],
  width: 387,
  height: 1111,
  popupItems: [],
  pointSize: 3,
  points: 93334240,
  measures: [
    {
      type: 'float8',
      name: 'lon',
      value: 'pickup_longitude',
      label: 'pickup_longitude',
      as: 'lon',
      format: 'auto',
      isCustom: false,
      expression: 'gis_mapping_lon',
    },
    {
      type: 'float8',
      name: 'lat',
      value: 'pickup_latitude',
      label: 'pickup_latitude',
      as: 'lat',
      format: 'auto',
      isCustom: false,
      expression: 'gis_mapping_lat',
    },
    {
      type: 'float8',
      name: 'color',
      value: 'total_amount',
      label: 'total_amount',
      as: 'color',
      format: 'auto',
      isCustom: false,
      expression: 'project',
    },
  ],
  selfFilter: {},
  bounds: {
    _sw: {lng: -74.11666788786385, lat: 40.11006460157117},
    _ne: {lng: -73.71601957345399, lat: 40.98403497397541},
  },
  colorKey: 'blue_green_yellow',
  ruler: {min: 2.5, max: 64.404},
  rulerBase: {min: 2.5, max: 220},
  filter: {},
};
export const PointConfigLackLonMeasure = {
  id: 'pointmap',
  type: 'PointMap',
  title: '纽约出租车总收入',
  mapTheme: 'mapbox://styles/mapbox/dark-v9',
  source: 'nyc_taxi',
  isServerRender: true,
  layout: {
    w: 12,
    h: 29.5,
    x: 0,
    y: 0,
    i: 'pointmap',
    minW: 1,
    minH: 8,
    moved: false,
    static: false,
  },
  center: {lng: -73.91634373065904, lat: 40.54847545087728},
  zoom: 9.407634540298755,
  dimensions: [],
  width: 387,
  height: 1111,
  popupItems: [],
  pointSize: 3,
  points: 93334240,
  measures: [
    {
      type: 'float8',
      name: 'lat',
      value: 'pickup_latitude',
      label: 'pickup_latitude',
      as: 'lat',
      format: 'auto',
      isCustom: false,
      expression: 'gis_mapping_lat',
    },
    {
      type: 'float8',
      name: 'color',
      value: 'total_amount',
      label: 'total_amount',
      as: 'color',
      format: 'auto',
      isCustom: false,
      expression: 'project',
    },
  ],
  selfFilter: {},
  bounds: {
    _sw: {lng: -74.11666788786385, lat: 40.11006460157117},
    _ne: {lng: -73.71601957345399, lat: 40.98403497397541},
  },
  colorKey: 'blue_green_yellow',
  ruler: {min: 2.5, max: 64.404},
  rulerBase: {min: 2.5, max: 220},
  filter: {},
};
export const HistogramConfig = {
  id: 'id_yipst7g838',
  type: 'HistogramChart',
  source: 'nyc_taxi',
  layout: {
    w: 12,
    h: 9.833333333333334,
    x: 12,
    y: 0,
    i: 'id_yipst7g838',
    minW: 1,
    minH: 5,
    moved: false,
    static: false,
  },
  dimensions: [
    {
      name: 'x',
      format: 'auto',
      type: 'DATE',
      value: 'tpep_dropoff_datetime',
      label: 'tpep_dropoff_datetime',
      isBinned: true,
      extract: false,
      as: 'x',
      expression: '',
      min: 'Wed Apr 01 00:01:45 2009',
      currMin: 'Wed Apr 01 00:01:45 2009',
      max: 'Fri May 01 00:44:00 2009',
      currMax: 'Fri May 01 00:44:00 2009',
      extent: ['Wed Apr 01 00:01:45 2009', 'Fri May 01 00:44:00 2009'],
      staticRange: ['Wed Apr 01 00:01:45 2009', 'Fri May 01 00:44:00 2009'],
      timeBin: 'day',
      binningResolution: '1d',
    },
  ],
  measures: [
    {
      type: 'float',
      name: 'y',
      value: 'avg(tip_amount/fare_amount)',
      label: '小费比例',
      as: 'y',
      format: ',.2%',
      isCustom: true,
      expression: 'project',
    },
  ],
  filter: {},
  selfFilter: {
    selfFilter_color: {
      type: 'filter',
      expr: {type: 'in', set: ['VTS', 'CMT', 'DDS'], expr: 'VendorID'},
    },
  },
  isShowRange: false,
  colorItems: [
    {color: '#37A2DA', as: 'y', label: '小费比例', value: 'avg(tip_amount/fare_amount)'},
  ],
  sort: {name: '', order: 'descending'},
  title: '小费平均占比',
  stackType: 'vertical',
};
export const HeatConfig = {
  id: 'id_6ikbyivj3hk',
  type: 'HeatChart',
  source: 'nyc_taxi',
  layout: {
    w: 6,
    h: 29.5,
    x: 24,
    y: 0,
    i: 'id_6ikbyivj3hk',
    minW: 1,
    minH: 5,
    moved: false,
    static: false,
  },
  dimensions: [
    {
      name: 'x',
      format: 'auto',
      type: 'DATE',
      value: 'tpep_pickup_datetime',
      isBinned: true,
      extract: true,
      as: 'x',
      min: 1,
      currMin: 1,
      max: 7,
      currMax: 7,
      extent: ['Thu Jan 01 00:00:00 2009', 'Fri Jan 02 23:59:59 2009'],
      staticRange: ['Thu Jan 01 00:00:00 2009', 'Fri Jan 02 23:59:59 2009'],
      timeBin: 'isodow',
      label: '',
    },
    {
      name: 'y',
      format: 'auto',
      type: 'DATE',
      value: 'tpep_pickup_datetime',
      isBinned: true,
      extract: true,
      as: 'y',
      min: 1,
      currMin: 1,
      max: 24,
      currMax: 24,
      extent: ['Thu Jan 01 00:00:00 2009', 'Fri Jan 02 23:59:59 2009'],
      staticRange: ['Thu Jan 01 00:00:00 2009', 'Fri Jan 02 23:59:59 2009'],
      timeBin: 'hour',
      binningResolution: '1h',
      label: '',
    },
  ],
  measures: [
    {
      type: 'float',
      name: 'color',
      value: 'avg(tip_amount/fare_amount)',
      label: '小费平均占比',
      as: 'color',
      format: '.0%',
      isCustom: true,
      expression: 'project',
      color: '#67E0E3',
    },
  ],
  colorKey: 'blue_green_yellow',
  title: '小费平均占比',
  ruler: {min: 0.03, max: 0.07},
  rulerBase: {min: 0.03, max: 0.07},
  filter: {},
  selfFilter: {},
};
export const BarConfig = {
  id: 'id_m0hd0jjwsy8',
  type: 'BarChart',
  title: '乘客数量平均值',
  source: 'nyc_taxi',
  layout: {
    w: 6,
    h: 12.291666666666666,
    x: 12,
    y: 9.833333333333334,
    i: 'id_m0hd0jjwsy8',
    minW: 1,
    minH: 5,
    moved: false,
    static: false,
  },
  dimensions: [
    {
      format: 'auto',
      type: 'DATE',
      value: 'tpep_dropoff_datetime',
      isBinned: true,
      extract: true,
      as: 'tpep_dropoff_datetime_anbgn8nnq9k',
      min: 0,
      currMin: 0,
      max: 23,
      currMax: 23,
      extent: ['Thu Jan 01 00:00:00 2009', 'Sat Jan 03 19:57:00 2009'],
      staticRange: ['Thu Jan 01 00:00:00 2009', 'Sat Jan 03 19:57:00 2009'],
      timeBin: 'hour',
      binningResolution: '1h',
      label: 'tpep_dropoff_datetime',
    },
  ],
  measures: [
    {
      type: 'int4',
      name: 'width',
      value: 'passenger_count',
      label: 'passenger_count',
      as: 'width',
      format: ',.2f',
      isCustom: false,
      expression: 'avg',
      color: '#37A2DA',
    },
    {
      type: 'float8',
      name: 'color',
      value: 'tip_amount',
      label: 'tip_amount',
      as: 'color',
      format: 'auto',
      isCustom: false,
      expression: 'avg',
    },
  ],
  limit: 12,
  colorKey: 'blue_green_yellow',
  sort: {order: 'descending', name: 'width'},
  ruler: {min: 0.43, max: 0.6},
  rulerBase: {min: 0.43, max: 0.6},
  filter: {},
  selfFilter: {},
};
export const PieConfigLackDimension = {
  id: 'id_9auxgreu1ri',
  type: 'PieChart',
  source: 'nyc_taxi',
  layout: {
    w: 6,
    h: 12.291666666666666,
    x: 18,
    y: 9.833333333333334,
    i: 'id_9auxgreu1ri',
    minW: 1,
    minH: 5,
    moved: false,
    static: false,
  },
  dimensions: [],
  measures: [
    {
      type: 'float',
      name: 'size',
      value: 'count(*)',
      label: '交易数量',
      as: 'size',
      format: 'auto',
      isCustom: true,
      expression: 'project',
      color: '#9d96f5',
    },
  ],
  limit: 12,
  colorKey: 'ordinal4',
  sort: {name: '', order: 'descending'},
  title: '出租车公司交易数量',
  filter: {id_f9u26y3uq8v: {type: 'filter', expr: "VendorID = 'CMT'"}},
  selfFilter: {},
};
export const NumberConfig = {
  id: 'id_4o7whbyjggl',
  type: 'NumberChart',
  source: 'nyc_taxi',
  dimensions: [],
  measures: [
    {
      type: 'float',
      name: 'value',
      value: 'avg(tip_amount/fare_amount)',
      label: '小费平均占比',
      as: 'value',
      format: ',.2%',
      isCustom: true,
      expression: 'project',
      color: '#fb7293',
    },
  ],
  layout: {
    w: 6,
    h: 7.375,
    x: 12,
    y: 22.125,
    i: 'id_4o7whbyjggl',
    minW: 1,
    minH: 5,
    moved: false,
    static: false,
  },
  colorKey: '#37A2DA',
  title: '小费平均占比',
  filter: {},
};
