#pragma once

#include "zcommon/log/log.h"


namespace zilliz {
namespace render {
namespace engine {

#define RENDER_ENGINE_DOMAIN_NAME "RENDER_ENGINE"

#define RENDER_ENGINE_LOG_TRACE _ZILLIZ_LOG_TRACE(RENDER_ENGINE_DOMAIN_NAME)

#define RENDER_ENGINE_LOG_DEBUG _ZILLIZ_LOG_DEBUG(RENDER_ENGINE_DOMAIN_NAME)
#define RENDER_ENGINE_LOG_INFO _ZILLIZ_LOG_INFO(RENDER_ENGINE_DOMAIN_NAME)
#define RENDER_ENGINE_LOG_WARNING _ZILLIZ_LOG_WARNING(RENDER_ENGINE_DOMAIN_NAME)
#define RENDER_ENGINE_LOG_ERROR _ZILLIZ_LOG_ERROR(RENDER_ENGINE_DOMAIN_NAME)
#define RENDER_ENGINE_LOG_FATAL _ZILLIZ_LOG_FATAL(RENDER_ENGINE_DOMAIN_NAME)

} // namespace engine
} // namespace render
} // namespace zilliz
