# Usage:
#   conda build . -c defaults -c conda-forge

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v').replace('-', '.') + environ.get('VERSION_SUFFIX', '') %}
# {% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_hash=environ.get('GIT_DESCRIBE_HASH', 'g1234567') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
  name: arctern-webserver
  version: {{ version }}

source:
  path: ../../..

# ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-section
build:
  number: {{ git_revision_count }}
  string: {{ git_revision_hash }}_{{ git_revision_count }}

requirements:
  build:
    - python ===3.7.6
    - setuptools
    - pandas ===1.0.3
    - flask ===1.1.1
    - waitress ===1.4.3
    - flask-httpauth ===3.3.0
    - flask-cors ===3.0.8
    - requests ===2.23.0
    - retrying ===1.3.3

  run:
    - python ===3.7.6
    - pandas ===1.0.3
    - flask ===1.1.1
    - waitress ===1.4.3
    - flask-httpauth ===3.3.0
    - flask-cors ===3.0.8
    - requests ===2.23.0
    - retrying ===1.3.3

test:
  commands:
    - python -c "import arctern_server"

about:
  home: http://www.github.com/zilliztech/arctern
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary:  Web server for Arctern
