package:
  name: arctern
  version: 0.1.0

source:
  path: ../../..

build:
  number: 0

requirements:
  build:
    - python ==3.8
    - gdal ==3.0.4
    - pyarrow ==0.15.1
    - gtest
    - rapidjson ==1.1.0
    - Cython ==0.29.15
    - pytest
  run:
    - python ===3.8
    - gdal ==3.0.4
    - pyarrow ===0.15.1
    - rapidjson ==1.1.0
    - Cython ==0.29.15

# test:
#   commands:
#     - python -c "import zilliz_gis"
#     - python -c "import zilliz_pyspark"

about:
  home: http://www.github.com/zilliztech/GIS
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary:  arctern core library
