apiVersion: v1
kind: Pod
metadata:
  name: arctern-cpu-build-env
  labels:
    app: arctern
    componet: cpu-build-env
spec:
  containers:
  - name: arctern-cpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.3.1-ubuntu18.04
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "127d784931114aa5e2a9a1c56aeb76398fe4042b8f856b0e5ae0fc83983fe7ca"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule
