apiVersion: v1
kind: Pod
metadata:
  name: arctern-gpu-build-env
  labels:
    app: arctern
    componet: gpu-build-env
spec:
  containers:
  - name: arctern-gpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.1.0-ubuntu18.04-gpu
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "473db02988f6a0796e0339e8d600fdedc5052a4749d11be82454e0dc070d1a89"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
        # nvidia.com/gpu: 1
        aliyun.com/gpu-mem: 2 # GiB
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule