apiVersion: v1
kind: Pod
metadata:
  name: arctern-cpu-build-env
  labels:
    app: arctern
    componet: cpu-build-env
spec:
  containers:
  - name: arctern-cpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.1.1-centos7
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "6299d8fe50f2a187c307e5dc2011842610a51dc0f212ee340c0561f6ffba87b2"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule
