apiVersion: v1
kind: Pod
metadata:
  name: arctern-cpu-build-env
  labels:
    app: arctern
    componet: cpu-build-env
spec:
  containers:
  - name: arctern-cpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.3.1-centos7
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "0d355e14b7961a0647a98c4968fb8436f7243b18136686e004fed4f7cc447634"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule
