apiVersion: v1
kind: Pod
metadata:
  name: arctern-cpu-build-env
  labels:
    app: arctern
    componet: cpu-build-env
spec:
  containers:
  - name: arctern-cpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.1.0-ubuntu18.04
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "e7fe40e2d322a5053fe488945aceb5902ee79700ede24e21bf5cc1caff2f67f3"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule
