apiVersion: v1
kind: Pod
metadata:
  name: arctern-cpu-build-env
  labels:
    app: arctern
    componet: cpu-build-env
spec:
  containers:
  - name: arctern-cpu-build-env
    image: registry.zilliz.com/arctern/arctern-build-env:v0.1.1-ubuntu18.04
    env:
    - name: OS_NAME
      value: "ubuntu18.04"
    - name: BUILD_ENV_IMAGE_ID
      value: "736b78afd1f71684291bd273b33e41fc3cf5e626f9ec0e58d69abd62a457b185"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "12Gi"
        cpu: "6.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule
