apiVersion: v1
kind: Pod
metadata:
  labels:
    app: env
    componet: docker
spec:
  containers:
  - name: docker-env
    image: registry.zilliz.com/library/docker:v1.1.0
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "6Gi"
        cpu: "2"
      requests:
        memory: "6Gi"
        cpu: "2"
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  tolerations:
  - key: dedicated
    operator: Equal
    value: arctern
    effect: NoSchedule