#!/usr/bin/env bash

export CUDA_VERSION=${CUDA_VERSION:="10.0"}
export BUILD_LIBARCTERN=1
export BUILD_ARCTERN=1
export BUILD_ARCTERN_SPARK=1
export UPLOAD_LIBARCTERN=1
export UPLOAD_ARCTERN=1
export UPLOAD_ARCTERN_SPARK=1
