name: CPP Build

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'cpp/**'
      - '.github/workflows/cpp.yml'
      - '!**.md'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'cpp/**'
      - '.github/workflows/cpp.yml'
      - '!**.md'
      - '!ci/jenkins/**'

jobs:
  ubuntu:
    name: AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout Arctern
        uses: actions/checkout@v1
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures ubuntu-cpp
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build ubuntu-cpp
          docker rmi $(docker images | grep '<none>' | awk '{print $3}') || exit 0
      - name: Docker Run
        run: |
          docker-compose run ubuntu-cpp
      - name: Upload coverage to Codecov
        if: success() && github.repository == 'zilliztech/arctern'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./ci/scripts/output_new.info
          name: amd64-linux-cpu-unittests
          flags: amd64_linux_cpu_unittests
          yml: ./codecov.yaml
      - name: Docker Push
        if: success() && github.event_name == 'push' && github.repository == 'zilliztech/arctern'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push ubuntu-cpp
