name: SCALA-TEST

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'scala/**'
      - '.github/workflows/scala.yml'
      - '!**.md'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'scala/**'
      - '.github/workflows/scala.yml'
      - '!**.md'
      - '!ci/jenkins/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Run scala test
        run: |
          docker build --tag scala-test:1804 . --file ./docker/scala/Dockerfile
          docker run -v ${GITHUB_WORKSPACE}/scala:/scala scala-test:1804
